/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio.pkg1;

import javax.swing.JOptionPane;

/**
 *
 * @author Payares
 */
public class interfazgrafica extends javax.swing.JFrame {

    /**
     * Creates new form interfazgrafica
     */
    public interfazgrafica() {
        initComponents();
    }
    public void borrar(){
         cantidad1.setText("");
        cantidad2.setText("");
        cantidad3.setText("");
        cantidad1.requestFocus();
        lbop1.setText("");
        lbop2.setText("");
        lbop3.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cantidad1 = new javax.swing.JTextField();
        cantidad2 = new javax.swing.JTextField();
        cantidad3 = new javax.swing.JTextField();
        cmbOperacion = new javax.swing.JButton();
        cmbBorrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbop3 = new javax.swing.JTextField();
        lbop2 = new javax.swing.JTextField();
        lbop1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Virtual DJ", 0, 14)); // NOI18N
        jLabel1.setText("Calculadora de porcentajes");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 11, -1, -1));

        jLabel2.setText("cantidad 1");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        jLabel3.setText("cantidad 2");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, -1, -1));

        jLabel4.setText("cantidad 3");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 124, -1, -1));

        cantidad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidad1KeyTyped(evt);
            }
        });
        jPanel2.add(cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 42, 184, -1));

        cantidad2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidad2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidad2KeyTyped(evt);
            }
        });
        jPanel2.add(cantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 80, 184, -1));

        cantidad3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidad3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidad3KeyTyped(evt);
            }
        });
        jPanel2.add(cantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 121, 184, -1));

        cmbOperacion.setText("Calcular");
        cmbOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOperacionActionPerformed(evt);
            }
        });
        cmbOperacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmbOperacionKeyTyped(evt);
            }
        });
        jPanel2.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 159, -1, -1));

        cmbBorrar.setText("Borrar");
        cmbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmbBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 71, -1));

        jLabel5.setText("Porcentaje 1");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 163, -1, -1));

        jLabel6.setText("Porcentaje 2");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 204, -1, -1));

        jLabel7.setText("Porcentaje 3");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 248, -1, -1));

        lbop3.setEditable(false);
        jPanel2.add(lbop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 240, 172, -1));

        lbop2.setEditable(false);
        jPanel2.add(lbop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 201, 172, -1));

        lbop1.setEditable(false);
        jPanel2.add(lbop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 160, 172, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 239, 71, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbOperacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbOperacionKeyTyped
     
        
    }//GEN-LAST:event_cmbOperacionKeyTyped

    private void cmbOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOperacionActionPerformed
String res1,res2,res3;
        /**/
        if (cantidad1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cantidad 1 vacía. Digítela", "error", JOptionPane.ERROR_MESSAGE);
        }
        else if (cantidad2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cantidad 2 vacía. Digítela", "error", JOptionPane.ERROR_MESSAGE);
        }
         else if (cantidad3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cantidad 3 vacía. Digítela", "error", JOptionPane.ERROR_MESSAGE);
        }
        else if (Double.parseDouble(cantidad1.getText()) == 0 && Double.parseDouble(cantidad2.getText()) == 0 && Double.parseDouble(cantidad3.getText()) == 0){
             JOptionPane.showMessageDialog(this,"Digita al menos un numero distinto a cero(0)","Error",JOptionPane.ERROR_MESSAGE);
             borrar();
            cantidad1.requestFocusInWindow();
        }
        else{
            
       double n1,n2,n3, suman=0;
        double op1,op2,op3;
        n1 = Double.parseDouble(cantidad1.getText());
        n2 = Double.parseDouble(cantidad2.getText());
        n3 = Double.parseDouble(cantidad3.getText());
        suman = n1 + n2 + n3;
        
        op1 = (n1 * 100)/suman;
        op2 = (n2 * 100)/suman;
        op3 = (n3 * 100)/suman;
        
        res1 = String.valueOf(op1);
        res2 = String.valueOf(op2);
        res3 = String.valueOf(op3);
        lbop1.setText(res1);
        lbop2.setText(res2);
        lbop3.setText(res3);
         }
    }//GEN-LAST:event_cmbOperacionActionPerformed

   
    private void cmbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBorrarActionPerformed
        // TODO add your handling code here:
        
       borrar();
        
        
    }//GEN-LAST:event_cmbBorrarActionPerformed

    private void cantidad1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad1KeyTyped
         char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume();
          }
    }//GEN-LAST:event_cantidad1KeyTyped

    private void cantidad2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad2KeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume();
          }
    }//GEN-LAST:event_cantidad2KeyPressed

    private void cantidad3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad3KeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume();
          }
    }//GEN-LAST:event_cantidad3KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cantidad2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad2KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume();
          }
    }//GEN-LAST:event_cantidad2KeyTyped

    private void cantidad3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad3KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume();
          }
    }//GEN-LAST:event_cantidad3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazgrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazgrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazgrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazgrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazgrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad1;
    private javax.swing.JTextField cantidad2;
    private javax.swing.JTextField cantidad3;
    private javax.swing.JButton cmbBorrar;
    private javax.swing.JButton cmbOperacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lbop1;
    private javax.swing.JTextField lbop2;
    private javax.swing.JTextField lbop3;
    // End of variables declaration//GEN-END:variables

}
